### ISSUE TITLE
Error running mkvirtualenv -p python3 on El Capitan

### ISSUE THREAD

**Issue by ariestiyansyah** [edx/openedxstats#25]
Error when run this command `mkvirtualenv -p python3 openedxstats` in OSX El Capitan.

```
☁  openedxstats [master] mkvirtualenv -p python3 openedxstats
Running virtualenv with interpreter /usr/local/bin/python3
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 14, in <module>
    import shutil
  File "/usr/local/Cellar/python3/3.4.3_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/shutil.py", line 11, in <module>
    import fnmatch
  File "/usr/local/Cellar/python3/3.4.3_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/fnmatch.py", line 15, in <module>
    import functools
  File "/usr/local/Cellar/python3/3.4.3_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/usr/local/Cellar/python3/3.4.3_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/collections/__init__.py", line 17, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/Library/Python/2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

**Comment by ariestiyansyah** [comment]
I fixed the error above by upgraded virtualenv 

`sudo pip install --upgrade virtualenv`

but if we get error like below when running this command `mkvirtualenv -p python3 openedxstats`

```
ImportError: cannot import name 'HTTPSHandler'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 2327, in <module>
    main()
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 711, in main
```

Solve it by update openssl and reinstall Python3.

```
# make a copy of the existing lib
sudo cp /usr/bin/openssl /usr/bin/openssl.apple

# update openssl 
brew update
brew install openssl
brew link --force openssl

# reload path
hash -r

# re-install python3
brew uninstall python3
brew install python3 --with-brewed-openssl
```

It solved my issue, hope it help.
